spring.application.name=email-sending
spring.output.ansi.enabled=ALWAYS

resend.api.key=re_6GkvzBUR_Fw4WjQH54KQpdG4RPXSVc1c1
resend.from=onboarding@resend.dev
resend.to=eyobajobi@gmail.com

server.port=8081
